### ISSUE TITLE
执行miniprogram-track scan发现的报错

### ISSUE THREAD

**Issue by bmjoker** [AEPKILL/miniprogram-track#2]
求解：
![image](https://github.com/AEPKILL/miniprogram-track/assets/37091232/0bea0c85-f519-4a5f-b0fe-a8be284b1741)
![image](https://github.com/AEPKILL/miniprogram-track/assets/37091232/af4a1d2a-4710-4816-8f09-8ecc08bddf52)
执行miniprogram-track scan发现的报错

**Comment by AEPKILL** [comment]
node 版本太低了，要 node 18+

**Comment by fpx183** [comment]
执行miniprogram-track scan
搜索不到微信包
