### ISSUE TITLE
执行miniprogram-track scan 搜索不到微信包

### ISSUE THREAD

**Issue by fpx183** [AEPKILL/miniprogram-track#3]
执行miniprogram-track scan
搜索不到微信包

**Comment by fpx183** [comment]
![image](https://github.com/AEPKILL/miniprogram-track/assets/126789824/df9d040f-bb83-4a33-be07-3e912ee91ed5)

**Comment by AEPKILL** [comment]
要在 PC 微信打开过的小程序才能被扫描到

**Comment by gqzszzy** [comment]
miniprogram-track scan
× 扫描失败，失败原因: fetch is not defined

**Comment by AEPKILL** [comment]
> miniprogram-track scan × 扫描失败，失败原因: fetch is not defined

#2
